spring:
  application:
    name: mbank-service

server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:87612/eureka